spring.application.name=GamingMicroservice
server.port=8081

#BD
spring.datasource.url=jdbc:postgresql://localhost:5433/gamingBD
spring.datasource.username=shopogolik
spring.datasource.password=freak
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Migration
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml

#AOP
spring.aop.auto=true