-- liquibase formatted sql

--changeset IvanTyapkin:1

CREATE TABLE users(
	id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	first_name VARCHAR(255),
	second_name VARCHAR(255),
    middle_name VARCHAR(255),
    user_id BIGINT,
	password TEXT,
	username TEXT
);

--changeset IvanTyapkin:2
ALTER TABLE users
ADD COLUMN role VARCHAR(255);

--changeset IvanTyapkin:3
CREATE INDEX user_name_index ON users (username);